## dev环境使用是配置
server:
  port: 8082
  context-path: /chao

#数据源
jdbc:
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://10.20.226.22:1433;databaseName=BakLaneDB
  userName: sa
  password: coing

pic:
  path: D:\result\192.168.0.195\
  type: .jpg
timer:
  scandir: 0 0/1 * * * *
##每分钟执行一次，如果当天有文件增加，就保存


##车道程序无用 - 为了程序正常加载
socket:
  stationID: 3211110060
  ip: 106.14.225.153
  port:
    server: 7712
    local: 65500
  xml:
    data: data.xml
    pic: pic.xml








