server:
  port: 65500
  context-path: /chao

#数据源
jdbc:
  driver-class-name: com.microsoft.jdbc.sqlserver.SQLServerDriver
  url: jdbc:microsoft:sqlserver://10.20.224.196:1433;DatabaseName=WOpenFerry
  userName: sa
  password: coing



http:
  limitWeight: 4900
  limit: 5
  host: http://localhost:65500/chao


##前置机无用和web无用
pic:
  path: D:\result\192.168.0.195\Record\
  type: .jpg
##永远不执行 每月的15号执行000
timer:
  scandir: 0 0 0 15 * ?
  ##每分钟执行一次
#  push: 0 0/1 * * * *
  push: 0/10 * * * * *



##车道程序无用 -前置机无用 - 为了程序正常加载
socket:
  stationID: 3211110060
  ip: 106.14.225.153
  port:
    server: 7712
    local: 65501
  xml:
     data: data.xml
     pic: pic.xml

